# Generated by Django 5.1.3 on 2025-01-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="cur_date",
            field=models.DateField(
                auto_now_add=True, db_index=True, verbose_name="날짜"
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="cur_nm",
            field=models.CharField(max_length=100, verbose_name="화폐 이름"),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="cur_unit",
            field=models.CharField(
                db_index=True, max_length=10, verbose_name="화폐 단위"
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="deal_bas_r",
            field=models.FloatField(verbose_name="현재 환율"),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="ttb",
            field=models.FloatField(default=0.0, verbose_name="사실 때"),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="tts",
            field=models.FloatField(default=0.0, verbose_name="파실 때"),
        ),
        migrations.AddConstraint(
            model_name="exchange",
            constraint=models.UniqueConstraint(
                fields=("cur_unit", "cur_date"), name="cur_unit_date"
            ),
        ),
    ]
